# Generated by Django 5.2.4 on 2025-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_auth', '0002_alter_calendaruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
